#!/bin/sh
# MultiWA API container entrypoint.
#
# Goal: `cp .env.docker .env && docker compose up -d` must boot securely with
# ZERO manual secret setup, while never shipping a usable secret in git.
#
# On first start this generates strong, unique JWT/encryption secrets and
# persists them to the sessions volume. Because the compose file runs the API
# with NODE_ENV=production, the fail-fast guard in main.ts (validateSecurityConfig)
# would otherwise crash-loop on the weak/empty defaults — this script feeds it
# strong values instead. Operator-provided strong secrets always take precedence
# and are never overwritten.
set -e

# Persisted in the sessions volume so the secrets survive container recreate.
# ENCRYPTION_KEY MUST stay stable: a new key each boot makes previously-encrypted
# settings undecryptable.
SECRETS_FILE="${MULTIWA_SECRETS_FILE:-/data/sessions/.multiwa-secrets.env}"

# Values main.ts treats as weak/default, plus the committed .env placeholders.
# Any of these (or an empty value) is treated as "unset" and replaced.
is_weak() {
  case "$1" in
    "" \
    | "default-secret-change-me" \
    | "change-this-refresh-secret" \
    | "change-this-to-a-random-secret" \
    | "your-secure-generated-secret-key-here" \
    | "your-super-secret-jwt-key-change-in-production")
      return 0 ;;
    *) return 1 ;;
  esac
}

# Crypto-strong random via the bundled node runtime (openssl is not guaranteed
# in the slim image; node always is). $1 = bytes, $2 = encoding (base64|hex).
gen() { node -e "process.stdout.write(require('crypto').randomBytes($1).toString('$2'))"; }

# Read a single KEY='value' back from the persisted file. Values are base64/hex
# (no single quotes), so a simple sed extraction is safe.
persisted() {
  [ -f "$SECRETS_FILE" ] || return 0
  sed -n "s/^$1='\(.*\)'\$/\1/p" "$SECRETS_FILE" | head -n1
}

# Resolve one secret. Precedence: strong operator env > value persisted on a
# prior boot > freshly generated. A weak-but-set env value (e.g. compose's
# ${JWT_SECRET:-change-...} default) is treated as unset so it never reaches app.
resolve_secret() {
  name="$1"; bytes="$2"; enc="$3"
  eval "cur=\$$name"
  if [ -n "$cur" ] && ! is_weak "$cur"; then
    return 0
  fi
  p="$(persisted "$name")"
  if [ -n "$p" ] && ! is_weak "$p"; then
    eval "export $name=\"\$p\""
    return 0
  fi
  new="$(gen "$bytes" "$enc")"
  eval "export $name=\"\$new\""
  GENERATED=1
}

GENERATED=0
resolve_secret JWT_SECRET 48 base64
resolve_secret JWT_REFRESH_SECRET 48 base64
resolve_secret ENCRYPTION_KEY 32 hex

if [ "$GENERATED" = 1 ]; then
  mkdir -p "$(dirname "$SECRETS_FILE")"
  ( umask 177
    {
      echo "# Auto-generated by entrypoint-api.sh on first boot. Do NOT commit."
      echo "JWT_SECRET='$JWT_SECRET'"
      echo "JWT_REFRESH_SECRET='$JWT_REFRESH_SECRET'"
      echo "ENCRYPTION_KEY='$ENCRYPTION_KEY'"
    } > "$SECRETS_FILE"
  )
  echo "🔐 [entrypoint] generated + persisted strong secrets to $SECRETS_FILE"
  echo "   Override any of JWT_SECRET / JWT_REFRESH_SECRET / ENCRYPTION_KEY via env to use your own."
fi

# Sync the DB schema before booting. No migrations directory exists, so use
# `prisma db push` (idempotent: creates tables on a fresh DB, no-op if matched).
cd /app/packages/database && prisma db push --skip-generate || echo 'prisma db push failed; starting API anyway'
cd /app/apps/api && exec node dist/main.js
